//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JunkShop.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JunkShop.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap close {
            get {
                object obj = ResourceManager.GetObject("close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Information_icon {
            get {
                object obj = ResourceManager.GetObject("Information_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à -
        ///Potion
        ///Potion-2
        ///Hi-Potion
        ///Hi-Potion-2
        ///X-Potion
        ///Mega-Potion
        ///Phönix-Feder
        ///Mega-Phönix
        ///Elixir
        ///Final-Elixir
        ///Gegengift
        ///Goldene Nadel
        ///Augentropfen
        ///Echo-Kraut
        ///Weihwasser
        ///Mega-Pille
        ///Mega-Pille-2
        ///Heldensaft
        ///Heldentrank
        ///Göttersaft
        ///Göttertrank
        ///Shell-Stein
        ///Protes-Stein
        ///Aura-Stein
        ///Todesstein
        ///Holy-Stein
        ///Flare-Stein
        ///Meteor-Stein
        ///Ultima-Stein
        ///Gizar-Kraut
        ///Phönix-Flügel
        ///Feuer-Siegel
        ///Zelt
        ///Stall
        ///Hütte
        ///G-Potion
        ///G-Hi-Potion
        ///G-Mega-Potion
        ///G-Returner
        ///Namensschild
        ///Vergißmeinnicht
        ///HP-Buch        /// [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string ItemsListDe {
            get {
                return ResourceManager.GetString("ItemsListDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à -
        ///Potion
        ///Potion+
        ///Hi-Potion
        ///Hi-Potion+
        ///X-Potion
        ///Mega-Potion
        ///Phoenix Down
        ///Mega Phoenix
        ///Elixir
        ///Megalixir
        ///Antidote
        ///Soft
        ///Eye Drops
        ///Echo Screen
        ///Holy Water
        ///Remedy
        ///Remedy+
        ///Hero-Trial
        ///Hero
        ///Holy War-Trial
        ///Holy War
        ///Shell Stone
        ///Protect Stone
        ///Aura Stone
        ///Death Stone
        ///Holy Stone
        ///Flare Stone
        ///Meteor Stone
        ///Ultima Stone
        ///Gysahl Greens
        ///Phoenix Pinion
        ///Friendship
        ///Tent
        ///Pet House
        ///Cottage
        ///G-Potion
        ///G-Hi-Potion
        ///G-Mega-Potion
        ///G-Returner
        ///Rename Card
        ///Amnesia Greens
        ///HP-J Scroll
        ///Str-J Scroll
        ///Vit-J [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string ItemsListEn {
            get {
                return ResourceManager.GetString("ItemsListEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à -
        ///Poción
        ///Poción+
        ///Ultrapoción
        ///Ultrapoción+
        ///Poción X
        ///Omnipoción
        ///Cola de Fénix
        ///Omnifénix
        ///Elixir
        ///Superelixir
        ///Antídoto
        ///Aguja de oro
        ///Colirio
        ///Hierba del eco
        ///Agua bendita
        ///Panacea
        ///Panacea+
        ///Sal heroica beta
        ///Sal heroica
        ///Sal sagrada beta
        ///Sal sagrada
        ///Piedra Coraza
        ///Piedra Escudo
        ///Piedra Aura
        ///Piedra Muerte
        ///Piedra Sanctus
        ///Piedra Fulgor
        ///Piedra Meteo
        ///Piedra Artema
        ///Verdura Gysahl
        ///Ala de Fénix
        ///Señal de lealtad
        ///Tienda de lona
        ///Caseta
        ///Chalé
        ///Poción G.F.
        ///Ultrapoción G.F.
        ///Omnipoción G.F.
        ///Resucit [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string ItemsListEs {
            get {
                return ResourceManager.GetString("ItemsListEs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à -
        ///Potion
        ///Potion+
        ///Hypra-Potion
        ///Maxi potion
        ///Potion totale
        ///Méga potion
        ///MT-Psy
        ///Maxi MT-Psy
        ///Elixir
        ///Mégalixir
        ///Antidote
        ///Défijeur
        ///Lasik
        ///Bocca
        ///Eau bénite
        ///Remède
        ///Remède +
        ///1-20-Syble
        ///Invulnérable
        ///1-destructible
        ///Croisade
        ///Roc cosse
        ///Roc carapace
        ///Roc d&apos;Aura
        ///Roc mortel
        ///Roc sacré
        ///Roc flamboyant
        ///Roc Météore
        ///Roc Ultima
        ///ChocoLégume
        ///Golgotha
        ///Pen Pal
        ///Red Kross
        ///Zoologie
        ///Saindoux
        ///Potion GF
        ///Potion GF +
        ///Mégapotion GF
        ///Sel marin
        ///Carte baptême
        ///Décapaciteur
        ///Livret HP-A
        ///Livret Vgr-A
        ///Livret Dfs- [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string ItemsListFr {
            get {
                return ResourceManager.GetString("ItemsListFr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à -
        ///Pozione
        ///Pozione+
        ///Granpozione
        ///Granpozione+
        ///Extrapozione
        ///Megapozione
        ///Coda di Fenice
        ///Megafenice
        ///Elisir
        ///Megalisir
        ///Antidoto
        ///Ago Dorato
        ///Collirio
        ///Erba dell&apos;Eco
        ///Acquasanta
        ///Panacea
        ///Panacea+
        ///Med dell&apos;Eroe ß
        ///Med dell&apos;Eroe
        ///Med del Mago ß
        ///Med del Mago
        ///Gemma Shell
        ///Gemma Protect
        ///Gemma Aura
        ///Gemma Death
        ///Gemma Holy
        ///Gemma Flare
        ///Gemma Meteor
        ///Gemma Ultima
        ///Erba Ghisal
        ///Piuma di Fenice
        ///Superamico
        ///Tenda
        ///Cuccia
        ///Cottage
        ///Pozione G
        ///Granpozione G
        ///Megapozione G
        ///Rivitalizzatore G
        ///Carta d&apos;Identità        /// [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string ItemsListIt {
            get {
                return ResourceManager.GetString("ItemsListIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap revolver {
            get {
                object obj = ResourceManager.GetObject("revolver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] SF_Slapstick_Comic {
            get {
                object obj = ResourceManager.GetObject("SF_Slapstick_Comic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] SF_Slapstick_Comic_Bold {
            get {
                object obj = ResourceManager.GetObject("SF_Slapstick_Comic_Bold", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] SF_Slapstick_Comic_Bold_Oblique {
            get {
                object obj = ResourceManager.GetObject("SF_Slapstick_Comic_Bold_Oblique", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] SF_Slapstick_Comic_Oblique {
            get {
                object obj = ResourceManager.GetObject("SF_Slapstick_Comic_Oblique", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Revolver
        ///Kiastraight
        ///Schneide-Trigger
        ///Flame-Tan
        ///Spaltlanze
        ///Vergehen &amp; Strafe
        ///Löwenherz
        ///Metallknöchel
        ///Maverick
        ///Gauntlet
        ///Ehrgeiz
        ///Valiant
        ///Ulyssis
        ///Bismark
        ///Exetor
        ///Kettenpeitsche
        ///Slavenil-Schwanz
        ///Roter Skorpion
        ///Königinnenwache
        ///Vollmond-Ring
        ///Valküre
        ///Rising Sun
        ///Kardinal
        ///Shooting Star
        ///Flegel
        ///Morgenstern
        ///Mond und Sterne
        ///Traum oder Illusion
        ///Hyperion
        ///Nichts
        ///MG
        ///Katar
        ///Harpune.
        /// </summary>
        internal static string WeaponsListDe {
            get {
                return ResourceManager.GetString("WeaponsListDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Revolver
        ///Shear Trigger
        ///Cutting Trigger
        ///Flame Saber
        ///Twin Lance
        ///Punishment
        ///Lion Heart
        ///Metal Knuckle
        ///Maverick
        ///Gauntlet
        ///Ehrgeiz
        ///Valiant
        ///Ulysses
        ///Bismark
        ///Exeter
        ///Chain Whip
        ///Slaying Tail
        ///Red Scorpion
        ///Save the Queen
        ///Pinwheel
        ///Valkyrie
        ///Rising Sun
        ///Cardinal
        ///Shooting Star
        ///Flail
        ///Morning Star
        ///Crescent Wish
        ///Strange Vision
        ///Hyperion
        ///None
        ///Machine Gun
        ///Katal
        ///Harpoon.
        /// </summary>
        internal static string WeaponsListEn {
            get {
                return ResourceManager.GetString("WeaponsListEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Revólver
        ///Kiat Recto
        ///Curtis Revólver
        ///Curtis-Kiat
        ///Avenger-Ranurado
        ///Avenger-Súper
        ///Lionheart
        ///Guantes de Lucha
        ///Maverick
        ///Full Metal
        ///Ehrgeiz
        ///Valiant
        ///Ulises
        ///Bismark
        ///Exeter
        ///Látigo de Cadena
        ///Cola de Sleipnir
        ///Red Scorpion
        ///Gold Snake
        ///Luna Llena
        ///Valkiria
        ///Sol naciente
        ///Cardenal
        ///Lethal Wings
        ///Cadet
        ///Deadly Iron
        ///Cielo Nocturno
        ///Infalible
        ///Hyperion
        ///No usa armas
        ///Ametralladora
        ///Kathar
        ///Harpón.
        /// </summary>
        internal static string WeaponsListEs {
            get {
                return ResourceManager.GetString("WeaponsListEs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pistolame
        ///Nacre Blade
        ///Dragon Blade
        ///Sabreur
        ///Katana
        ///Kendo
        ///Lionheart
        ///Metal Gloves
        ///Maverick
        ///Gauntlets
        ///Ehrgeiz
        ///W.W.West
        ///Roosevelt
        ///Bertha
        ///Steel Gun
        ///Gibet
        ///Totally S.M.
        ///Red Scorpio
        ///Smiley
        ///Rotator
        ///Walkyrie
        ///Ninja Sun
        ///Ptérodactyle
        ///Tronçonneur
        ///Nunchak Red
        ///Nunchak Blue
        ///Islam Star
        ///Sagaie
        ///Hypérion
        ///Nada
        ///Kalachnikov
        ///Katal
        ///Harpoon.
        /// </summary>
        internal static string WeaponsListFr {
            get {
                return ResourceManager.GetString("WeaponsListFr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Revolver
        ///Kastlet
        ///Cutting Trigger
        ///Flame Tank
        ///Twin Lance
        ///Crime &amp; Penalty
        ///Lion Heart
        ///Metal Knuckle
        ///Maverick
        ///Gauntlet
        ///Ehrgeiz
        ///Valiant
        ///Ulysses
        ///Bismark
        ///Exeter
        ///Chain Whip
        ///Slaying Tail
        ///Red Scorpion
        ///Save the Queen
        ///Boomerfriz
        ///Valkyrie
        ///Rising Sun
        ///Cardinal
        ///Shooting Star
        ///Flail
        ///Morning Star
        ///Crescent Wish
        ///Strange Vision
        ///Hyperion
        ///None
        ///Machine Gun
        ///Katal
        ///Harpoon.
        /// </summary>
        internal static string WeaponsListIt {
            get {
                return ResourceManager.GetString("WeaponsListIt", resourceCulture);
            }
        }
    }
}
